# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Define Environment Variable at Runtime
          command: |
            echo 'export SECRET_KEY=1234' >> $BASH_ENV
            echo 'export ACCUWEATHER_API_KEY=1234' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install

      - run:
          name: run tests
          command: |
            pipenv run python manage.py collectstatic --noinput
            pipenv run python manage.py test --settings=weather.settings_test

      - store_artifacts:
          path: test-reports
          destination: test-reports
