# Generated by Django 2.0.6 on 2018-06-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherservice', '0003_forecastdatapoint_location_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastdatapoint',
            options={'ordering': ['datetime']},
        ),
        migrations.AddField(
            model_name='forecastdatapoint',
            name='data_point_type',
            field=models.CharField(choices=[('FORECAST', 'Forecast'), ('CURRENT_CONDITIONS', 'Current conditions')], default='FORECAST', max_length=32),
        ),
    ]
