# Generated by Django 2.0.6 on 2018-06-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherservice', '0004_auto_20180619_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastdatapoint',
            name='precipitation_probability',
            field=models.FloatField(default=0),
        ),
    ]
