# Generated by Django 2.0.6 on 2018-06-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherservice', '0008_auto_20180619_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=64)),
                ('accuweather_location_id', models.CharField(blank=True, max_length=64)),
                ('metaweather_location_id', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
