# Generated by Django 2.0.6 on 2018-06-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherservice', '0009_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='active_location',
            field=models.BooleanField(default=False),
        ),
    ]
