# Generated by Django 2.0.6 on 2018-06-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('precipitation_probability', models.FloatField()),
                ('weather_icon', models.CharField(max_length=128)),
                ('weather_icon_name', models.CharField(max_length=128)),
                ('mobile_link', models.CharField(max_length=512)),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
    ]
