# Generated by Django 2.0.6 on 2018-06-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accuweather', '0006_auto_20180619_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastdatapoint',
            name='precipitation_probability',
        ),
    ]
