# Generated by Django 2.0.6 on 2018-06-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accuweather', '0007_remove_forecastdatapoint_precipitation_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastdatapoint',
            name='temperature_max',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='forecastdatapoint',
            name='temperature_min',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forecastdatapoint',
            name='temperature',
            field=models.FloatField(default=0, null=True),
        ),
    ]
